#coding=utf-8
"""
Django settings for booksite project.

Generated by 'django-admin startproject' using Django 1.9.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'h@%0jr6h#6h9-votspfbnaa7u%pn&r5hsah41iet-a(af9dc*u'

# SECURITY WARNING: don't run with debug turned on in production!
#用于调试url的参数 当需要url调试时可以用 if settings.DEBUG,程序发布时改为False
DEBUG = True


ALLOWED_HOSTS = ['*']

#未处置异常时候发送邮件，包括终端警报（MANAGERS）也有类似选项设置
ADMINS = (
        ('Leo','lvze@cainiaoketang.com'),
        )


# Application definition
#激活app，是以项目目录为根，如果你的app不是在项目基目录下要注明路径
#django.contrib中邦汉Django自带的附加组件

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'books',
    'templateapp',
]
#中间件选项，如安全验证等,也可以是自己添加的中间件路径。
MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

#根项目url，指定url的查找位置
ROOT_URLCONF = 'booksite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['/home/lvze/templates/'],#指明模板的查找位置,如果不添加每个目录，app默认会查找自己目录下的模板文件夹，
                                          #添加后先查找这个目录如果没有找到相应模板再去app下的templates查找，如果添加多个目录则按顺序查找，知道找到制定模板
                                          #所以这里添加路径不利于模板名称的复用
        'APP_DIRS': True,
        'OPTIONS': {
            #RequestContext的全局设置，在这里添加后就无需在调用RequestContext时再次声明而是默认存在
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'booksite.views.custom_proc'     #模板高级全局RequestContext示例
            ],
        },
    },
]

WSGI_APPLICATION = 'booksite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases
'''
'ENGINE': 'django.db.backends.sqlite3',      #默认使用sqlite3
'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),#如果使sqlite那么只要添加数据库文件路径就可以
'''

DATABASES = {
    'default': {
        'ENGINE':'django.db.backends.mysql',#数据库引擎
        'NAME':'Bookdb',#数据库名
        'USER':'root',
        'PASSWORD':'123',
        'HOST':'', #指明登陆哪台主机的数据库及所用端口，如果是本机可以为空
        'PORT':'', 

    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/
# 默认为英语美国芝加哥时间，以下改为汉语上海时间
LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS  = (
        BASE_DIR,'static'
)

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_USE_TLS = False
EMAIL_HOST = 'smtp.126.com'
EMAIL_HOST_USER = 'lvze_work@126.com'
EMAIL_HOST_PASSWORD = 'lvze880321LZ'
DEFAULT_FROM_EMAIL = 'lvze_work@126.com'
